"""create_ppt_jobs_table

Revision ID: 1799ba7ee24b
Revises: 
Create Date: 2026-07-04 18:29:55.772148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1799ba7ee24b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ppt_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='关联的项目 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='任务状态: pending/running/completed/failed'),
    sa.Column('input_data', sa.Text(), nullable=True, comment='任务输入数据的 JSON 字符串'),
    sa.Column('output_path', sa.Text(), nullable=True, comment='生成文件路径'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败时的错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppt_jobs_project_id'), 'ppt_jobs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ppt_jobs_project_id'), table_name='ppt_jobs')
    op.drop_table('ppt_jobs')
    # ### end Alembic commands ###
